language: ruby
script: bundle exec rake build
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  
env:
  - RUBYGEMS_VERSION=2.0.3
  - RUBYGEMS_VERSION=1.8.25

before_install:
  - gem update --system $RUBYGEMS_VERSION
  - gem --version

matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.0.0
      env: RUBYGEMS_VERSION=1.8.25